version: '3'
services:
  api:
    build: ./ctrl-api
    ports:
      - "8088:8088"
    depends_on:
      - "geth"
      - "ipfs"
      - "mongo"
    networks:
      ctrl-net:
        ipv4_address: 172.111.66.2

  geth:
    image: ethereum/client-go:v1.8.15
    command: --rpc --rpcaddr 0.0.0.0 --ws --wsaddr 0.0.0.0 --dev --datadir "/root/.ethereum" --rpcapi eth,web3,net,web3,personal
    volumes:
      - /Users/Shared/gethdata:/root/.ethereum
    ports:
      - "30303:30303"
      - "8545:8545"
      - "8546:8546"
    networks:
      ctrl-net:
        ipv4_address: 172.111.66.3
  
  ipfs:
    image: ipfs/go-ipfs:v0.4.17
    volumes:
      - /tmp/ipfs-docker-staging:/export
      - /tmp/ipfs-docker-data:/data/ipfs
    ports:
      - "8080:8080"
      - "4001:4001"
      - "5001:5001"
    networks:
      ctrl-net:
        ipv4_address: 172.111.66.4

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      ctrl-net:
        ipv4_address: 172.111.66.5

networks:
  ctrl-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - 
          subnet: 172.111.66.0/24
